### Check database connection
GET {{url}}/api/databaseConnected
Content-Type: application/json
Authorization: Bearer {{token}}

### Get user files
GET {{url}}/api/filelist
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Upload file
POST {{url}}/api/upload
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{auth_token}}

--boundary
Content-Disposition: form-data; name="files"; filename="input.txt"

// The 'input.txt' file will be uploaded
< ./input.txt

### Get file
GET {{url}}/api/download?id=8
Authorization: Bearer {{auth_token}}
