### Send new user balance
POST {{url}}/api/auth/login
Content-Type: application/json

{
  "username": "manager",
  "password": "manager"
}

> {%
    client.global.set('auth_token',response.body.access_token);
    client.global.set('refresh_token',response.body.refresh_token);
%}

### Send new user balance
POST {{url}}/api/auth/refresh-token
Content-Type: application/json

{
  "token": "{{refresh_token}}"
}

> {%
    client.global.set('auth_token',response.body.access_token);
    client.global.set('refresh_token',response.body.refresh_token);
%}



### Send new user balance
GET {{url}}/api/checkAuth
Content-Type: application/json
Authorization: Bearer {{auth_token}}

